name: Build and Publish Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Publish the plugin
        run: dotnet publish -o ./publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MqttCovePlugin
          path: ./publish/MqttCovePlugin.dll
